server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studysystem?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

#mybatis:
#  mapper-location: classpath:**/*.xml

logging:
  level:
    com.scut.demo.dao: debug

mybatis:
  mapper-locations: classpath:/mappers/*.xml
